# Generated by Django 3.1.7 on 2021-07-24 14:12

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
