# Generated by Django 3.1.7 on 2021-10-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20211026_1542'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categorytask', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='professions',
            field=models.ManyToManyField(to='authapp.Professions', verbose_name='профессии'),
        ),
    ]
