# Generated by Django 3.1.7 on 2021-04-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
