# Generated by Django 3.1.7 on 2021-07-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionneedprofessions',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
