# Generated by Django 3.1.7 on 2021-07-03 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        ('groupapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='done_task',
            field=models.ManyToManyField(blank=True, related_name='done_task', to='mainapp.Task'),
        ),
        migrations.AddField(
            model_name='group',
            name='got_task',
            field=models.ManyToManyField(null=True, related_name='got_task', to='mainapp.Task'),
        ),
        migrations.AddField(
            model_name='group',
            name='need_profession',
            field=models.ManyToManyField(through='groupapp.DescriptionNeedProfessions', to='authapp.Professions'),
        ),
        migrations.AddField(
            model_name='group',
            name='team_members',
            field=models.ManyToManyField(through='groupapp.MemberTeam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descriptionneedprofessions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupapp.group'),
        ),
        migrations.AddField(
            model_name='descriptionneedprofessions',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.professions'),
        ),
        migrations.AddField(
            model_name='applicationtoneedprofession',
            name='author_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtoneedprofession',
            name='to_need_profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupapp.descriptionneedprofessions'),
        ),
    ]
