# Generated by Django 3.1.7 on 2021-04-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0002_auto_20210410_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'команда', 'verbose_name_plural': 'команды'},
        ),
    ]
