# Generated by Django 3.1.7 on 2021-10-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20211013_1859'),
        ('groupapp', '0003_auto_20211013_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoneedprofession',
            name='to_need_profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupapp.descriptionneedprofessions', verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='descriptionneedprofessions',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='descriptionneedprofessions',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.professions', verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='group',
            name='need_profession',
            field=models.ManyToManyField(through='groupapp.DescriptionNeedProfessions', to='authapp.Professions', verbose_name='нужные профессии'),
        ),
    ]
