# Generated by Django 3.1.7 on 2021-04-21 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupapp', '0003_auto_20210414_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
