# Generated by Django 3.1.7 on 2021-10-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0004_auto_20211013_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoneedprofession',
            name='description_self',
            field=models.TextField(blank=True, verbose_name='расскажите о себе'),
        ),
    ]
