# Generated by Django 3.1.7 on 2021-10-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0005_auto_20211013_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='logotype',
            field=models.ImageField(blank=True, upload_to='group_avatars', verbose_name='логотип'),
        ),
    ]
