# Generated by Django 3.1.7 on 2021-04-05 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='date_updata_profile',
            new_name='date_update_profile',
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_end', models.BooleanField(default=False)),
                ('back_end', models.BooleanField(default=False)),
                ('web_designer', models.BooleanField(default=False)),
                ('ux_designer', models.BooleanField(default=False)),
                ('game_designer', models.BooleanField(default=False)),
                ('android', models.BooleanField(default=False)),
                ('ios', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='profession',
            field=models.ManyToManyField(blank=True, to='authapp.Professions'),
        ),
    ]
