# Generated by Django 3.1.7 on 2021-05-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professions',
            name='discretion',
            field=models.CharField(blank=True, max_length=240, verbose_name='требования'),
        ),
    ]
