# Generated by Django 3.1.7 on 2021-04-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210405_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='user_instagram',
            field=models.URLField(blank=True, verbose_name='инстаграмм'),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='user_phone',
            field=models.CharField(max_length=20, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='user_telegram',
            field=models.URLField(blank=True, verbose_name='телеграмм'),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='user_vk',
            field=models.URLField(blank=True, verbose_name='вконтакте'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='android',
            field=models.BooleanField(default=False, verbose_name='android разработчик'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='back_end',
            field=models.BooleanField(default=False, verbose_name='back-end разработчик'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='front_end',
            field=models.BooleanField(default=False, verbose_name='front-end разработчик'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='game_designer',
            field=models.BooleanField(default=False, verbose_name='game дизайнер'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='ios',
            field=models.BooleanField(default=False, verbose_name='ios разработчик'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='ux_designer',
            field=models.BooleanField(default=False, verbose_name='UX дизайнер'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='web_designer',
            field=models.BooleanField(default=False, verbose_name='web дизайнер'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='about_me',
            field=models.CharField(blank=True, max_length=1000, verbose_name='обо мне'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatars', verbose_name='аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='date_born',
            field=models.DateField(null=True, verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='profession',
            field=models.ManyToManyField(blank=True, to='authapp.Professions', verbose_name='профессии'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='фамилия'),
        ),
    ]
