# Generated by Django 3.1.7 on 2021-10-13 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211010_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 18, 45, 55, 55585, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
