# Generated by Django 3.1.7 on 2021-04-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210405_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactuser',
            options={'verbose_name': 'контакты', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='professions',
            options={'verbose_name': 'профессии', 'verbose_name_plural': 'профессии'},
        ),
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
