# Generated by Django 3.1.7 on 2021-10-15 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20211013_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 9, 40, 45, 842663, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
