# Generated by Django 3.1.7 on 2021-11-09 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20211101_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 14, 59, 59, 461770, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
