# Generated by Django 3.1.7 on 2021-07-30 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='сообщения')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('is_active', models.BooleanField(default=True, verbose_name='удалено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageapp.dialog', verbose_name='чат')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
